Fix shellcheck bash lint tool warnings.
Adjust shell scripts to avoid raising "shellcheck -x" warnings.  This
should be maintained going forward.

diff --git a/gin_hexedit b/gin_hexedit
--- a/gin_hexedit
+++ b/gin_hexedit
@@ -9,27 +9,27 @@
 usage() {
   cat <<EOM
   Usage:
-  $(basename $0) relname
+  $(basename "$0") relname
 
 EOM
   exit 0
 }
 
-[ -z $1 ] && { usage; }
+[ -z "$1" ] && { usage; }
 
 source ./hexedit.cfg
 
 relname=$1
 
 # Print useful byte offsets for user to stdout:
-psql --no-psqlrc  -c "CREATE EXTENSION IF NOT EXISTS pageinspect"
-if [ ! $? -eq 0 ]; then
+if ! psql --no-psqlrc -c "CREATE EXTENSION IF NOT EXISTS pageinspect"
+then
   echo "creating pageinspect extension failed"
   exit
 fi
 
 echo "Contiguous flags in GIN index summary:"
-psql --no-psqlrc -P pager=off -c "WITH recursive index_details AS (
+if ! psql --no-psqlrc -P pager=off -c "WITH recursive index_details AS (
   SELECT '$relname'::text AS idx
 ),
 size_in_pages_index AS (
@@ -83,12 +83,11 @@ WHERE
   series = first
 ORDER BY
   first;"
-
-if [ ! $? -eq 0 ]; then
-   echo "displaying contiguous range of blocks failed"
-   exit
+then
+  echo "displaying contiguous range of blocks failed"
+  exit
 fi
 
 export OFFSETS=""
-echo "Note: no offsets are set in cache when using $(basename $0) convenience script"
-./__open_relation $relname
+echo "Note: no offsets are set in cache when using $(basename "$0") convenience script"
+./__open_relation "$relname"
diff --git a/relation_hexedit b/relation_hexedit
--- a/relation_hexedit
+++ b/relation_hexedit
@@ -7,13 +7,13 @@
 usage() {
   cat <<EOM
   Usage:
-  $(basename $0) relname
+  $(basename "$0") relname
 
 EOM
   exit 0
 }
 
-[ -z $1 ] && { usage; }
+[ -z "$1" ] && { usage; }
 
 source ./hexedit.cfg
 
@@ -24,7 +24,7 @@ relname=$1
 #
 # Note that the query will return NULL for very small relations, which leaves
 # us without any cached offsets.
-export OFFSETS=$(psql --no-psqlrc -tA -c "WITH offsets (block_offset) AS (
+if ! OFFSETS=$(psql --no-psqlrc -tA -c "WITH offsets (block_offset) AS (
   SELECT unnest(percentile_cont(array[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]) WITHIN GROUP (ORDER BY i))::int8 * (2^13)
   FROM
   (SELECT i FROM generate_series(1, LEAST(131071, (SELECT (pg_relation_size('$relname'::regclass) / (2^13))::int4) - 1)) i ) s
@@ -35,6 +35,11 @@ nums (num, bb_offset) AS (
   offsets ORDER BY BLOCK_OFFSET
 )
 SELECT string_agg('GoToOffset' || num || '=' || bb_offset, chr(10)) FROM nums;")
+then
+  echo "calculating decile offsets failed"
+  exit
+fi
 
+export OFFSETS
 echo "Tip: 'Go to Offset' dialog (shortcut: Ctrl + G) will have decile splitter block start positions cached"
-./__open_relation $relname
+./__open_relation "$relname"
