Raise error when wxHexEditor is missing.
The convenience scripts will now specifically report on the fact that a
wxHexEditor executable was not found at the configured path.

diff --git a/relation_hexedit b/relation_hexedit
--- a/relation_hexedit
+++ b/relation_hexedit
@@ -83,6 +83,12 @@ if [ ! $? -eq 0 ]; then
   exit
 fi
 
+if [ ! -f $HEXEDITOR ]; then
+  echo "\"$HEXEDITOR\" executable not found"
+  echo "\"$FULLPATH.tags\" annotation file was still created"
+  exit 1
+fi
+
 echo "Opening $FULLPATH with $HEXEDITOR..."
 echo "Tip: 'Go to Offset' dialog (shortcut: Ctrl + G) has decile splitter block start positions cached"
 # Output from wxHexEditor is verbose, and not terribly useful, so we redirect:
